version: '3.9'

services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=archiso
      - POSTGRES_DB=db