
@url = http://localhost:8080/api/v1

### Login 
POST {{url}}/auth/login
Content-Type: application/json

{
  "username": "archiso",
  "password": "1234"
}

### register
POST {{url}}/auth/register
Content-Type: application/json

{
  "username": "archiso",
  "email": "archiso@gmail.com",
  "password": "1234",
  "display": "ArchISO"
}


### Verify
GET {{url}}/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcmNoaXNvMiIsImlhdCI6MTcwNDU4MDU2MiwiZXhwIjoxNzA0NjY2OTYyfQ.QiQIoIm9dp-HJJzuGFbPox4TI9SR3G-SitdAS4OBTk0


### Create Fortress
POST {{url}}/fortress
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcmNoaXNvIiwiaWF0IjoxNzA0NTkyMzMxLCJleHAiOjE3MDQ2Nzg3MzF9.D86B0j7QWrpju_GN8FzBfUul4KX9PReDCccZvuP9fQc
Content-Type: application/json

{
  "fortname": "fortress-linux",
  "display": "Linux OS | I want this!"
}

### GET FORTRESSES
GET {{url}}/fortress
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcmNoaXNvIiwiaWF0IjoxNzA0NTgwNjYzLCJleHAiOjE3MDQ2NjcwNjN9.c2DZIFvgJhFTRsjKCJ7VXuCC71BpX5UV9dnjCbq51eA