
@url = http://localhost:8080/api/v1

### Login 
POST {{url}}/auth/login
Content-Type: application/json

{
  "username": "archiso",
  "password": "1234"
}

### register
POST {{url}}/auth/register
Content-Type: application/json

{
  "username": "archiso",
  "email": "archiso@gmail.com",
  "password": "1234",
  "display": "ArchISO"
}


### Verify
GET {{url}}/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.2eyJzdWIiOiJhcmNoaXNvIiwiaWF0IjoxNzA0NTU5NTUyLCJleHAiOjE3MDQ2NDU5NTJ9.5TvM3kqpLXqTH-Y7pbVkGRNTZrcxYVTcOwJ7yL-02b4